#!/usr/bin/env sh

export PATH="/usr/local/bin:$PATH"
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# =================== Debug Output and Error Reporting =====================
yabai -m config debug_output on

# ===================== Tiling Options ====================
# bsp: stack or float
yabai -m config layout bsp
# new window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement first_child
# set all padding and gaps to 20pt (default: 0)
yabai -m config top_padding    10
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     10

yabai -m config split_ratio 0.5

# =================== Mouse Settings ====================
# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize
# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action swap
# ==================== Menu bar Modifications ====================
yabai -m config external_bar all:30:0

# ===================== Window Modifications ====================
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9
yabai -m config window_shadow float
yabai -m config insert_feedback_color 0xff9dd274

# ===================== Window Animations =====================
yabai -m config window_opacity_duration 0.10
yabai -m config window_animation_duration 0.25 # faster animations
yabai -m config window_animation_easing ease-in-out # smoother easing function

# =================== Disable specific apps from being managed with yabai ==================
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off


borders active_color=0xff00ff00 inactive_color=0xff494d64 width=3.0 &

echo "yabai configuration loaded.."
